### ISSUE TITLE
from albumentations import DualIAATransform, to_tuple ImportError: cannot import name 'DualIAATransform' from 'albumentations' (J:\ComfyUI\python_embeded\lib\site-packages\albumentations_init_.py)

### ISSUE THREAD

**Issue by xianrenzhang0318** [hhhzzyang/Comfyui_Lama#2]
Traceback (most recent call last):
  File "J:\ComfyUI\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "J:\ComfyUI\ComfyUI\custom_nodes\Comfyui_Lama\__init__.py", line 1, in <module>
    from .LamaRemove import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "J:\ComfyUI\ComfyUI\custom_nodes\Comfyui_Lama\LamaRemove.py", line 13, in <module>
    from saicinpainting.training.trainers import load_checkpoint
  File "J:\ComfyUI\ComfyUI\custom_nodes\Comfyui_Lama\saicinpainting\training\trainers\__init__.py", line 3, in <module>
    from saicinpainting.training.trainers.default import DefaultInpaintingTrainingModule
  File "J:\ComfyUI\ComfyUI\custom_nodes\Comfyui_Lama\saicinpainting\training\trainers\default.py", line 7, in <module>
    from saicinpainting.training.data.datasets import make_constant_area_crop_params
  File "J:\ComfyUI\ComfyUI\custom_nodes\Comfyui_Lama\saicinpainting\training\data\datasets.py", line 20, in <module>
    from saicinpainting.training.data.aug import IAAAffine2, IAAPerspective2
  File "J:\ComfyUI\ComfyUI\custom_nodes\Comfyui_Lama\saicinpainting\training\data\aug.py", line 1, in <module>
    from albumentations import DualIAATransform, to_tuple
ImportError: cannot import name 'DualIAATransform' from 'albumentations' (J:\ComfyUI\python_embeded\lib\site-packages\albumentations\__init__.py)

I am using the latest version of albumentations-1.3.1, and the above problem occurs, but I see that lama requires albumentations==0.5.2. I don’t know if it will conflict with other nodes.

**Comment by xianrenzhang0318** [comment]
import imgaug.augmenters as iaa
from albumentations import DualIAATransform, to_tuple


I modified the code of aug.py and it actually works. Of course I am a newbie in programming.

**Comment by LionBuer** [comment]
> import imgaug.augmenters as iaa from albumentations import DualIAATransform, to_tuple
> 
> I modified the code of aug.py and it actually works. Of course I am a newbie in programming.

请问你是怎么修改的？我也遇到了相同的问题

**Comment by lldacing** [comment]
> > import imgaug.augmenters as iaa from albumentations import DualIAATransform, to_tuple
> > I modified the code of aug.py and it actually works. Of course I am a newbie in programming.
> 
> 请问你是怎么修改的？我也遇到了相同的问题

改成
from albumentations import DualTransform as DualIAATransform
from albumentations.core.utils import to_tuple
