### ISSUE TITLE
ModuleNotFoundError: No module named 'models.ade20k'

### ISSUE THREAD

**Issue by xianrenzhang0318** [hhhzzyang/Comfyui_Lama#5]
Traceback (most recent call last):
  File "J:\ComfyUI\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "J:\ComfyUI\ComfyUI\custom_nodes\Comfyui_Lama\__init__.py", line 1, in <module>
    from .LamaRemove import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "J:\ComfyUI\ComfyUI\custom_nodes\Comfyui_Lama\LamaRemove.py", line 12, in <module>
    from saicinpainting.evaluation.utils import move_to_device
  File "J:\ComfyUI\ComfyUI\custom_nodes\Comfyui_Lama\saicinpainting\evaluation\__init__.py", line 6, in <module>
    from saicinpainting.evaluation.losses.base_loss import SSIMScore, LPIPSScore, FIDScore
  File "J:\ComfyUI\ComfyUI\custom_nodes\Comfyui_Lama\saicinpainting\evaluation\losses\base_loss.py", line 13, in <module>
    from models.ade20k import SegmentationModule, NUM_CLASS, segm_options
ModuleNotFoundError: No module named 'models.ade20k'

**Comment by 1ikeman** [comment]
Has this problem been solved? I have this problem too

**Comment by bluetyhyhf** [comment]
I'm having the same problem!
