### ISSUE TITLE
load failed

### ISSUE THREAD

**Issue by chris1024hub** [hhhzzyang/Comfyui_Lama#9]
Traceback (most recent call last):
  File "L:\chris-download\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "L:\chris-download\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_Lama\__init__.py", line 1, in <module>
    from .LamaRemove import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "L:\chris-download\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_Lama\LamaRemove.py", line 13, in <module>
    from saicinpainting.training.trainers import load_checkpoint
  File "L:\chris-download\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_Lama\saicinpainting\training\trainers\__init__.py", line 3, in <module>
    from saicinpainting.training.trainers.default import DefaultInpaintingTrainingModule
  File "L:\chris-download\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_Lama\saicinpainting\training\trainers\default.py", line 7, in <module>
    from saicinpainting.training.data.datasets import make_constant_area_crop_params
  File "L:\chris-download\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_Lama\saicinpainting\training\data\datasets.py", line 20, in <module>
    from saicinpainting.training.data.aug import IAAAffine2, IAAPerspective2
  File "L:\chris-download\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_Lama\saicinpainting\training\data\aug.py", line 1, in <module>
    from albumentations import DualIAATransform, to_tuple
ImportError: cannot import name 'DualIAATransform' from 'albumentations' (L:\chris-download\ComfyUI_windows_portable\python_embeded\Lib\site-packages\albumentations\__init__.py)

Cannot import L:\chris-download\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_Lama module for custom nodes: cannot import name 'DualIAATransform' from 'albumentations' (L:\chris-download\ComfyUI_windows_portable\python_embeded\Lib\site-packages\albumentations\__init__.py)

**Comment by LeoMusk** [comment]
same+1

**Comment by LeoMusk** [comment]
还没能解决吗o(╥﹏╥)o
